---
- name: Vector | Download rpm
  become: true
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
    dest: "./vector-{{ vector_version }}-1.x86_64.rpm"
    mode: "0644"
    timeout: 200
- name: Vector | Install package
  become: true
  become_method: sudo
  ansible.builtin.yum:
    disable_gpg_check: true
    name: "./vector-{{ vector_version }}-1.x86_64.rpm"
  ignore_errors: "{{ ansible_check_mode }}"