---
- name: Vector | Download rpm
  become: true
  ansible.builtin.get_url:
    url: "https://packages.timber.io/vector/{{ vector_version }}/vector-{{ vector_version }}-1.x86_64.rpm"
    dest: "./vector-{{ vector_version }}-1.x86_64.rpm"
    mode: "0644"
    timeout: 200
- name: Vector | Install package
  become: true
  become_method: sudo
  ansible.builtin.yum:
    disable_gpg_check: true
    name: "./vector-{{ vector_version }}-1.x86_64.rpm"
  ignore_errors: "{{ ansible_check_mode }}"
- name: Vector | Create data dir
  become: true
  ansible.builtin.file:
    mode: "755"
    path: "{{ vector_config_dir }}"
    state: "directory"
- name: Vector | Template config
  become: true
  ansible.builtin.template:
    src: "templates/vector.config.j2"
    dest: "{{ vector_config_dir }}/vector.yaml"
    mode: "755"
- name: Vector | Register service
  become: true
  ansible.builtin.template:
    src: "templates/vector.service.j2"
    dest: "/etc/systemd/system/vector.service"
    mode: "0644"
    backup: true
  notify: start-vector
