---
- name: Include tasks install CentOS
  ansible.builtin.include_tasks: install/CentOS.yml
  when: ansible_distribution == "CentOS"

- name: Include tasks install Ubuntu
  ansible.builtin.include_tasks: install/Ubuntu.yml
  when: ansible_distribution == "Ubuntu"

- name: Vector | Create data dir
  become: true
  ansible.builtin.file:
    mode: "755"
    path: "{{ vector_config_dir }}"
    state: "directory"
- name: Vector | Template config
  become: true
  ansible.builtin.template:
    src: "templates/vector.config.j2"
    dest: "{{ vector_config_dir }}/vector.yaml"
    mode: "755"
- name: Vector | Register service
  become: true
  ansible.builtin.template:
    src: "templates/vector.service.j2"
    dest: "/etc/systemd/system/vector.service"
    mode: "0644"
    backup: true
  notify: start-vector
