---
dependency:
  name: galaxy
  options:
    ignore-errors: True
driver:
  name: docker
lint: |
  ansible-lint .
  yamllint .
platforms:
  - name: ubuntu1804
    hostname: ubuntu1804
    image: geerlingguy/docker-ubuntu1804-ansible:latest
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
    override_command: false

  - name: ubuntu2004
    hostname: ubuntu2004
    image: geerlingguy/docker-ubuntu2004-ansible:latest
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
    override_command: false

  - name: centos7
    hostname: centos7
    image: geerlingguy/docker-centos7-ansible:latest
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
    override_command: false

  - name: centos8
    hostname: centos8
    image: geerlingguy/docker-centos8-ansible:latest
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
    override_command: false
provisioner:
  name: ansible
verifier:
  name: ansible
