---
dependency:
  name: galaxy
  options:
    ignore-errors: True
driver:
  name: podman
lint: |
  ansible-lint .
  yamllint .
platforms:
  - name: centos7
    hostname: centos7
    image: docker.io/library/centos:7
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
    override_command: false
provisioner:
  name: ansible
verifier:
  name: ansible
